#spring.application.name=hogwarts-artifacts-online
spring:
  datasource:
    url: jddbc:h2:mem:hogwarts
    username: sa
    password:
      driver-class-name: org.h2.Driver
      jpa:
        show-sql:true;

